services:
  php:
    build: 
      context: ..
      dockerfile: docker/php/Dockerfile
    container_name: payerjuarez-api-php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - payerjuarez-bootstrap-cache:/var/www/bootstrap/cache
      - payerjuarez-storage:/var/www/storage
    environment:
      - APP_NAME=${APP_NAME}
      - APP_TIMEZONE=${APP_TIMEZONE}
      - APP_LOCALE=${APP_LOCALE}
      - APP_KEY=${APP_KEY}
      - APP_ENV=production
      - APP_DEBUG=false

      - SUPER_ADMIN_NAME=${SUPER_ADMIN_NAME}
      - SUPER_ADMIN_EMAIL=${SUPER_ADMIN_EMAIL}
      - SUPER_ADMIN_PHONE=${SUPER_ADMIN_PHONE}
      - SUPER_ADMIN_PASSWORD=${SUPER_ADMIN_PASSWORD}

      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    networks:
      - mysql
      - php

  nginx:
    build: 
      context: ..
      dockerfile: docker/nginx/Dockerfile
    container_name: payerjuarez-api-nginx
    restart: unless-stopped
    volumes:
      - payerjuarez-storage:/var/www/storage:ro
    expose:
      - "80"   
    depends_on:
      - php
    networks:
      - proxy
      - php

networks:
  proxy:
    external: true
  mysql:
    external: true
  php:

volumes:
  payerjuarez-bootstrap-cache:
  payerjuarez-storage: